language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - if [[ "$(phpenv version-name)" != "hhvm" ]]; then echo 'short_open_tag = On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - mysql -e 'CREATE DATABASE concrete5_tests;'
  - cd web/concrete
  - composer install
  - cd ../../tests

script: phpunit

notifications:
  email: false
  irc: "irc.freenode.org#concrete5-dev"
